### ISSUE TITLE
Coverage information missing

### ISSUE THREAD

**Issue by hph** [keplersj/jest-runner-prettier#7]
I noticed that `collectCoverage: true` does not work with this test runner. Is this something that can't be supported or just an implementation detail? I noticed that this project has two Jest configs, one with coverage on and another without. I'd personally want to avoid running Jest twice, and saw this project as a nice way of testing that formatting had been done without another command.

I'd personally be fine with disabling this runner when coverage information really is required (like in CI environments), but it seems like this is an oversight and it complicates setup a bit. I'd be happy to help in fixing this, if you think it should be.

**Comment by keplersj** [comment]
Coverage support can be added.. I'm not sure how helpful it would be though. If you want to implement it as an optional feature I'd happily take the PR.

I know the configuration in the repo looks a little clunky, that's in part because the configuration is dogfooding so that it lints itself, but I can assure you that Jest is running only once with this configuration. I need to do some research into how Jest handles subconfigurations like this though - that might make some of the configuration simpler.

**Comment by hph** [comment]
My original issue was probably a bit vague so I'll try to clarify what I meant.

Basically, I have a project with some tests in it and when I run Jest I can opt into seeing their coverage of the codebase by passing `--coverage` (or configuring Jest otherwise). Now, after setting `"runner": "jest-runner-prettier"` I no longer get the coverage output. Again, this is easily mitigated by creating separate development and CI Jest config files, but it seemed like it shouldn't have to be necessary. It appears that the code coverage information that Jest collects from the tests is lost somewhere in the process (or possibly it's not supported by custom runners at all).

Anyway - I might look into this further at some point and if I do figure something out I'll let you know. In the meantime, feel free to close this issue. Thanks!

**Comment by keplersj** [comment]
It sounds to me like you've set this to be your project's runner instead of the built in runner and your tests aren't running anymore and instead are being checked for prettiness. I recommend watching the ["Jest as a Platform" talk](https://www.youtube.com/watch?v=NtjyeojAOBs) from ReactiveConf 2017 where they discuss using multiple Jest test runners in a project.

**Comment by hph** [comment]
Ah - you're absolutely right. I'll have a look, thanks!

**Comment by keplersj** [comment]
Happy to help! 😀

**Comment by hph** [comment]
In case anyone finds this and is in a similar situation, I ended up setting up my project with [multiple Jest config files](https://github.com/hph/wings/tree/master/config/jest) in order to run Prettier, ESLint and the test suite in one go. Pretty handy!
